### ISSUE TITLE
[BUG] Results from row data quality checks not matching actual record counts

### ISSUE THREAD

**Issue by PKJ-x7** [Nike-Inc/spark-expectations#101] opened 2024-06-13 11:52 UTC
I have a table with **45M** records. 
One of the columns has nearly **8.8 nulls**; however, the Spark Expectations null check result gives only **1M** rows as failed_row_count. 
Similarly, the counts for unique values in a column are also not correct. 

This is from the row_dq_res_summary:
 {'description': 'shipment_nbr should not be null',
  'tag': 'spark_test',
  'rule': 'shipment_nbr_null_validation',
  'rule_type': 'row_dq',
  'failed_row_count': '999142',
  'action_if_failed': 'ignore'}]

and, the expectation as defined: "shipment_nbr is not null"

The code was executed in Python on a Databricks notebook with a cluster having DBR 9.1 LTS and Spark 3.1.2

Additional context:
The table with 0 nulls in columns being tested, passed the spark expectations checks and results also showed 0 failed_row_count.

**Comment by IMC07** [comment] 2024-06-13 14:27
Hi PKJ, which version of spark-expectations were you using?

**Comment by PKJ-x7** [comment] 2024-06-14 07:04
I installed it in a Databricks cluster via pypi. I think it's 2.1.0
<img width="1526" alt="Screenshot 2024-06-14 at 12 33 08 PM" src="https://github.com/Nike-Inc/spark-expectations/assets/85632179/b521ca4f-1ab3-49ff-bdbb-cdfc1da85504">

**Comment by PKJ-x7** [comment] 2024-06-19 05:12
Are there any updates team?

**Comment by shinga** [comment] 2024-06-26 16:28
Hi, I was facing the same issue. For my use case, I am joining some tables, creating a new df on top of the output inside build_new(), and running expectations on top of it. I believe the root cause is here:
https://github.com/Nike-Inc/spark-expectations/blob/d3edcde55d309b8765419f065193c409b17de12a/spark_expectations/sinks/utils/writer.py#L882-L894
The error_df is joining on this id but the monotonically_increasing_id() is not deterministic. When I ran this, I could see in the spark plan that my df was being recomputed. I was able to sidestep this issue by adding `write_to_temp=True`. Since monotonically_increasing_id() is assigned based on partition ids, this seems to add some consistency.

**Comment by asingamaneni** [comment] 2024-06-26 20:53
@shinga Thanks for the analysis. Let me know if you want to pick this issue or we will prioritize this for the next release!

**Comment by ManduriRaja** [comment] 2024-07-02 06:49
@asingamaneni  We Would like to pick up this issue and contribute.

**Comment by asingamaneni** [comment] 2024-07-02 14:20
Thanks, assigned to you

**Comment by ManduriRaja** [comment] 2024-07-02 22:13
@shinga  Will be working on this bug and will keep you posted.

**Comment by shinga** [comment] 2024-07-09 21:34
Hi @asingamaneni , for this bug I think it would be best to just revert the changes to this function. Since the recent updates were made to improve performance, here are some ideas we could explore instead:

- `error_df` is computed when writing to the error table, getting error count, and getting summarized row_dq results. If error_table is enabled and error_table_writer_config is overwrite, it should be faster to read error_df from the error table after writing to it, so that error_df does not need to be recomputed when getting the error count and the summarized row_dq results.
- If the user knows that the error dataset is expected to be small, we could add an optional parameter to cache the `error_df` instead of the above.

**Closed** 2024-07-16 15:40 UTC
Labels: bug
