### ISSUE TITLE
[BUG] The overall error count doesn't match with detail counts in "row_dq_res_summary" in the stats table

### ISSUE THREAD

**Issue by IMC07** [Nike-Inc/spark-expectations#62] opened 2024-01-04 09:02 UTC
**Describe the bug**
The error count observed in the column "error_count" of stats table doesn't match with count in "row_dq_res_summary" field.

**To Reproduce**
Steps followed:

Executed Spark Expectations with only 1 "row_dq" rule types. The one rule failed. Stats was updated successfully with no issues.

Error_count field in the stats was: 76

Row_dq_res_summary showed:
0: {"description": "test duplicates", "tag": "uniqueness", "rule": "test_duplicates", "rule_type": "row_dq", "failed_row_count": "26", "action_if_failed": "ignore"}

This behavior of the counts not matching up was observed over multiple runs, also with more tests.

**Expected behavior**
I expected the counts to be equal.

**Comment by jskrajareddy21** [comment] 2024-02-12 19:50
Both below codes are working fine. Please check with these and let us know if you are facing same issue .
**code 1:**
`def generate_summarised_row_dq_res(self, df: DataFrame, rule_type: str) -> None:
    """
    This function implements/supports summarising row dq error result
    Args:
        df: error dataframe(DataFrame)
        rule_type: type of the rule(str)

    Returns:
        None

    """
    try:
        error_df_data = df.select(explode(f"meta_{rule_type}_results").alias("row_dq_res")) \
            .rdd.map(
             lambda rule_meta_dict: (
                 rule_meta_dict[0]["rule_type"],rule_meta_dict[0]["description"],rule_meta_dict[0]["rule"],rule_meta_dict[0]["tag"],rule_meta_dict[0]["action_if_failed"],
                 {**rule_meta_dict[0], "failed_row_count": 1},
             )).toDF().groupBy("_1","_2","_3","_4","_5").count()
        error_df_data_rename = error_df_data.withColumnRenamed("_1","rule_type").withColumnRenamed(
             "_2", "description").withColumnRenamed("_3", "rule").withColumnRenamed("count",
                                                                                   "failed_row_count").withColumnRenamed(
             "_4", "tag").withColumnRenamed("_5", "action_if_failed").select("rule_type", "description", "rule",
                                                                             "failed_row_count", "tag",
                                                                             "action_if_failed")
        error_df_data_agg_map = error_df_data_rename.withColumn("row_dq_res",
                            create_map(lit("rule_type"), col("rule_type"), lit("description"), col("description"),
                                       lit("rule"), col("rule"), lit("failed_row_count"), col("failed_row_count"),
                                       lit("tag"), col("tag"), lit("action_if_failed"), col("action_if_failed")))
        error_df_data_agg_map_summary = error_df_data_agg_map.groupBy("rule_type").agg(collect_list("row_dq_res").alias("row_dq_res_new"))

        self._context.set_summarised_row_dq_res(error_df_data_agg_map_summary.collect()[0][1])
    except Exception as e:
        raise SparkExpectationsMiscException(
            f"error occurred created summarized row dq statistics {e}"
        )`

</hr>
code 2:
`def generate_summarised_row_dq_res(self, df: DataFrame, rule_type: str) -> None:
    """
    This function implements/supports summarising row dq error result
    Args:
        df: error dataframe(DataFrame)
        rule_type: type of the rule(str)

    Returns:
        None

    """
    try:
        df_exploded = df.select(explode(f"meta_{rule_type}_results").alias("row_dq_res"))
        keys = df_exploded.select(explode("row_dq_res")).select("key").distinct().rdd.flatMap(lambda x:x).collect()
        nested_keys = [col("row_dq_res").getItem(k).alias(k) for k in keys]
        df_select = df_exploded.select(*nested_keys)
        df_pivot = df_select.groupBy(df_select.columns).count().withColumnRenamed("count", "failed_row_count")
        keys += ["failed_row_count"]
        summarised_row_dq_list = df_pivot.rdd.map(lambda x: {i: x[i] for i in keys}).collect()
        print(summarised_row_dq_list)
        self._context.set_summarised_row_dq_res(summarised_row_dq_list)
    except Exception as e:
        raise SparkExpectationsMiscException(
            f"error occurred created summarised row dq statistics {e}"
        )`

**Note**:  ReduceByKey method is inconsistently giving count.

**Comment by asingamaneni** [comment] 2024-02-12 21:36
Closing this as the issue is fixed!

**Closed** 2024-03-07 16:50 UTC
Labels: bug
